# Generated by Django 4.1.2 on 2022-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5000)),
                ('slug', models.CharField(max_length=5000, unique=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=5000)),
                ('slug', models.CharField(max_length=5000, unique=True)),
                ('description', models.CharField(max_length=5000)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
