# Generated by Django 4.1.2 on 2022-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traadwik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=1000)),
                ('description_1', models.CharField(max_length=5000)),
                ('description_2', models.CharField(blank=True, max_length=5000, null=True)),
                ('description_3', models.CharField(blank=True, max_length=5000, null=True)),
                ('description_4', models.CharField(blank=True, max_length=5000, null=True)),
                ('description_5', models.CharField(blank=True, max_length=5000, null=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('contact_email', models.EmailField(default='careers@satikelectric.co.in', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=5000)),
                ('img', models.ImageField(default='/noProductImage.png', upload_to='priceList/img')),
                ('pdf', models.FileField(upload_to='priceList/documents')),
                ('slug', models.CharField(max_length=5000, unique=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
