# Generated by Django 4.1.2 on 2022-11-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traadwik', '0003_alter_jobs_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(default='/noProductImage.png', upload_to='priceList/img'),
        ),
    ]
