# Generated by Django 4.1.2 on 2022-11-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traadwik', '0004_productcategory_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5000)),
                ('slug', models.CharField(max_length=5000, unique=True)),
                ('short_description', models.CharField(max_length=10000)),
                ('brand', models.CharField(choices=[('schneider', 'Schneider'), ('legrand', 'Legrand')], default='schneider', max_length=8000)),
                ('subcategory', models.CharField(default='Schneider', max_length=8000)),
                ('img1', models.ImageField(default='/noProductImage.png', upload_to='productImg/')),
                ('Feature_1_title', models.CharField(max_length=5000)),
                ('Feature_1_description', models.CharField(max_length=10000)),
                ('priceList', models.FileField(upload_to='priceList/documents')),
                ('priceList_2', models.FileField(blank=True, null=True, upload_to='priceList/documents')),
                ('priceList_3', models.FileField(blank=True, null=True, upload_to='priceList/documents')),
                ('p_warranty', models.CharField(blank=True, max_length=5000, null=True)),
                ('Feature_2_title', models.CharField(blank=True, max_length=5000, null=True)),
                ('Feature_2_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('Feature_3_title', models.CharField(blank=True, max_length=5000, null=True)),
                ('Feature_3_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('Feature_4_title', models.CharField(blank=True, max_length=5000, null=True)),
                ('Feature_4_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('Feature_5_title', models.CharField(blank=True, max_length=5000, null=True)),
                ('Feature_5_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('Full_1_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('Full_2_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('Full_3_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('Full_4_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='productImg/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='productImg/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='productImg/')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='productImg/')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='productImg/')),
                ('img7', models.ImageField(blank=True, null=True, upload_to='productImg/')),
                ('img8', models.ImageField(blank=True, null=True, upload_to='productImg/')),
            ],
        ),
    ]
